version: '3.7'

services:
  mongodb-finance:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-finance
    environment:
      MONGO_INITDB_DATABASE: db_finance
    ports:
      - 27017:27017
    volumes:
      - ./db-finance:/data/db